In [1]:
import numpy

In [21]:
#numpy is a python package. it stands for numerical python 
#it is a library consisting of multidimensional array object and a collection of routines for processing of array

In [3]:
numpy.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [4]:
numpy.array([11,12,13,14,15])

array([11, 12, 13, 14, 15])

In [2]:
import numpy as np

In [6]:
a=np.array([90,92,93,88,55,76,12,35])

In [7]:
a

array([90, 92, 93, 88, 55, 76, 12, 35])

In [8]:
a.shape

(8,)

In [9]:
b=np.array([10,20,30,40,50,60,70,80,90,100])

In [10]:
b

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [11]:
b.shape

(10,)

In [12]:
a=np.array([[1,2],[3,4]])

In [13]:
a

array([[1, 2],
       [3, 4]])

In [14]:
a.shape

(2, 2)

In [15]:
b=np.array([[11,12],[13,14],[15,16]])

In [16]:
b

array([[11, 12],
       [13, 14],
       [15, 16]])

In [17]:
b.shape

(3, 2)

In [18]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
c.shape

(3, 3)

In [22]:
d=np.array([[1,2,3],[4,5,6]])

In [23]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
d.shape

(2, 3)

In [25]:
e=np.array([[11,12],[13,14],[15,16]])

In [26]:
e

array([[11, 12],
       [13, 14],
       [15, 16]])

In [27]:
e.shape

(3, 2)

In [28]:
g=np.array([[4,6],[8,3],[9,5]])
g

array([[4, 6],
       [8, 3],
       [9, 5]])

In [29]:
g.reshape(2,3)

array([[4, 6, 8],
       [3, 9, 5]])

In [30]:
b=np.array([[78,90],[22,33]])

In [31]:
b

array([[78, 90],
       [22, 33]])

In [32]:
b.min()

22

In [34]:
b.max()

90

In [35]:
b.shape

(2, 2)

In [36]:
 b.size

4

In [37]:
b.itemsize

4

In [38]:
b.dtype

dtype('int32')

In [39]:
b.data

In [40]:
f=np.array([[20,30,40],[50,60,70],[80,90,100]])

In [41]:
f

array([[ 20,  30,  40],
       [ 50,  60,  70],
       [ 80,  90, 100]])

In [42]:
f.shape

(3, 3)

In [43]:
f.size

9

In [44]:
f.itemsize

4

In [45]:
f.dtype

dtype('int32')

In [46]:
f.min()

20

In [47]:
f.max()

100

In [49]:
g=np.array([[1,2],[3,4],[5,6]],dtype='float64')
g

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [50]:
g.itemsize

8

In [51]:
g.shape

(3, 2)

In [52]:
g.dtype

dtype('float64')

In [53]:
g.min()

1.0

In [54]:
g.max()

6.0

In [55]:
g.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [56]:
g.ndim

2

In [57]:
y=np.arange(5)
y

array([0, 1, 2, 3, 4])

In [58]:
x=np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
a=x.reshape(3,5)

In [61]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
a=x.reshape(5,3)

In [63]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [64]:
x=np.arange(25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
a=x.reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [66]:
a=np.arange(35).reshape(5,7)
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [67]:
a.shape

(5, 7)

In [68]:
a.ndim

2

In [69]:
a.dtype

dtype('int32')

In [70]:
a.itemsize

4

In [71]:
type(a)

numpy.ndarray

In [72]:
a.size

35

In [73]:
b=np.array([6,7,8])

In [74]:
b

array([6, 7, 8])

In [75]:
b=np.array([[1.5,2,3],[4,5,6]],dtype='float32')

In [76]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]], dtype=float32)

In [77]:
ra=np.array([[34,78,89],[22,33,77]])

In [78]:
# ravel operation where you can convert one numpy array into a single row i,e ravel
print(ra.ravel())

[34 78 89 22 33 77]


In [79]:
b=np.array([[1.5,2,3],[4,5,6]],dtype='int32')
b

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
np.zeros([3,4])


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [88]:
np.ones([3,4],dtype='int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [89]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [92]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [94]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [96]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Broadcasting in numpy

In [97]:
a=np.array([1.0,2.0,3.0])
b=np.array([2.0,2.0,2.0])
a*b

array([2., 4., 6.])

In [98]:
a=np.array([1.0,2.0,3.0])
b=2.0
a*b

array([2., 4., 6.])

In [99]:
a=np.array([20,30,40,50])
b=np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [100]:
c=a-b

In [101]:
c

array([20, 29, 38, 47])

In [102]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [105]:
b=np.random.random([2,3])


In [106]:
b

array([[0.301034  , 0.77698124, 0.27476323],
       [0.80275387, 0.78228249, 0.48959707]])

In [107]:
c=np.ones([2,3])
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [108]:
d=b+c
d

array([[1.301034  , 1.77698124, 1.27476323],
       [1.80275387, 1.78228249, 1.48959707]])

universal functions

In [109]:
b=np.arange(3)

In [110]:
b

array([0, 1, 2])

In [111]:
np.exp(b)

array([1.        , 2.71828183, 7.3890561 ])

In [112]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356])

In [ ]:
indexing and slicing

In [6]:
np.random.seed(5)
print(np.random.rand(10,6))

[[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119 0.61174386]
 [0.76590786 0.51841799 0.2968005  0.18772123 0.08074127 0.7384403 ]
 [0.44130922 0.15830987 0.87993703 0.27408646 0.41423502 0.29607993]
 [0.62878791 0.57983781 0.5999292  0.26581912 0.28468588 0.25358821]
 [0.32756395 0.1441643  0.16561286 0.96393053 0.96022672 0.18841466]
 [0.02430656 0.20455555 0.69984361 0.77951459 0.02293309 0.57766286]
 [0.00164217 0.51547261 0.63979518 0.9856244  0.2590976  0.80249689]
 [0.87048309 0.92274961 0.00221421 0.46948837 0.98146874 0.3989448 ]
 [0.81373248 0.5464565  0.77085409 0.48493107 0.02911156 0.08652569]
 [0.11145381 0.25124511 0.96491529 0.63176605 0.8166602  0.566082  ]]


In [8]:
np.random.seed(6)
print(np.random.rand(10,6))

[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [10]:
print(np.random.randn(10,3))
np.random.seed(5)

[[-2.12647459  0.75144883 -0.54060704]
 [ 0.79322236  0.17365335 -1.03543429]
 [ 0.87426839 -0.73957208  0.52294535]
 [-0.59187648 -0.47748711  0.11252968]
 [ 1.90474232  0.69415315 -0.01958134]
 [ 1.66284285  0.03060843 -0.29749921]
 [-0.96813764  0.16706673  0.11660197]
 [-0.68225732 -1.91402115 -0.13990231]
 [ 0.11492459 -0.39500464 -0.95331626]
 [-1.07282736 -0.48444561  1.36293786]]


In [14]:
print(np.random.randn(10,3))

[[ 0.44122749 -0.33087015  2.43077119]
 [-0.25209213  0.10960984  1.58248112]
 [-0.9092324  -0.59163666  0.18760323]
 [-0.32986996 -1.19276461 -0.20487651]
 [-0.35882895  0.6034716  -1.66478853]
 [-0.70017904  1.15139101  1.85733101]
 [-1.51117956  0.64484751 -0.98060789]
 [-0.85685315 -0.87187918 -0.42250793]
 [ 0.99643983  0.71242127  0.05914424]
 [-0.36331088  0.00328884 -0.10593044]]


In [17]:
print(np.random.randn(10,3))

[[-0.58661296 -1.48185327  0.85724762]
 [ 0.94309899  0.11444143 -0.02195668]
 [-2.12714455 -0.83440747 -0.46550831]
 [ 0.23371059  1.38503523 -0.51962709]
 [-0.78015214  0.95560959 -0.12673638]
 [-1.36861282  1.21848065 -0.85750144]
 [-0.56147088 -1.0335199   0.35877096]
 [ 1.07368134 -0.37550472  0.39636757]
 [-0.47144628  2.33660781  1.50278553]
 [-0.59545972  0.52834106  0.9398248 ]]


In [18]:
print(np.random.randint(5,20,10))

[16 17 17 12 19 19 17 19 10 17]


In [19]:
print(np.random.randint(2,20,8))

[14  3 14 19  9  6 10 15]


In [20]:
print(np.random.randint(1,30,(6,7)))

[[ 8 25 17 11 13 14 13]
 [25 16 26 19  1 13 15]
 [15 24 23 17  8 28  6]
 [12  2 25  6 10 28 27]
 [23 20  8  8 12  6  4]
 [ 9 16  8  4 11  6 26]]


numpy condition

In [22]:
a=np.random.randint(1,40,10)

In [23]:
a

array([36, 15, 21, 30,  1,  9, 39, 36, 19, 34])

In [24]:
 np.clip(a,a_min=10,a_max=25)

array([25, 15, 21, 25, 10, 10, 25, 25, 19, 25])

In [26]:
print(np.where(a < 10)) #in gives index details

(array([4, 5], dtype=int64),)


In [27]:
print(np.where(a==36))

(array([0, 7], dtype=int64),)


Reshaping other ways

In [29]:
import numpy as np
from numpy.random import randint as ri 

In [30]:
a=ri(1,99,30)
a

array([87, 73, 89, 74, 33, 72, 17, 38, 47, 90, 45, 57, 46, 38, 74, 61,  2,
       66, 26, 26, 38, 92, 87, 85, 75, 17, 69, 55, 96, 67])

In [31]:
b=a.reshape(2,3,5) #tow matrixex 3rows and 5 columns
b

array([[[87, 73, 89, 74, 33],
        [72, 17, 38, 47, 90],
        [45, 57, 46, 38, 74]],

       [[61,  2, 66, 26, 26],
        [38, 92, 87, 85, 75],
        [17, 69, 55, 96, 67]]])

In [32]:
c=a.reshape(6,5)
c

array([[87, 73, 89, 74, 33],
       [72, 17, 38, 47, 90],
       [45, 57, 46, 38, 74],
       [61,  2, 66, 26, 26],
       [38, 92, 87, 85, 75],
       [17, 69, 55, 96, 67]])

In [33]:
c.min()

2

In [34]:
c.max()

96

Sorting

In [35]:
m=ri(1,100,25).reshape(5,5)

In [36]:
m

array([[13, 50, 48, 15, 95],
       [27, 65, 92,  3,  3],
       [86, 65, 40, 12, 87],
       [39, 43, 17, 10, 22],
       [30, 64, 96, 59, 25]])

In [37]:
np.sort(m)#sorting row wise

array([[13, 15, 48, 50, 95],
       [ 3,  3, 27, 65, 92],
       [12, 40, 65, 86, 87],
       [10, 17, 22, 39, 43],
       [25, 30, 59, 64, 96]])

In [38]:
np.sort(m,axis=0)#sorting column wise

array([[13, 43, 17,  3,  3],
       [27, 50, 40, 10, 22],
       [30, 64, 48, 12, 25],
       [39, 65, 92, 15, 87],
       [86, 65, 96, 59, 95]])

In [40]:
arr=np.arange(13,30)
print(arr)

[13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [41]:
print(arr[7])

20


In [42]:
print(arr[3:6])

[16 17 18]


In [43]:
arr[4:]

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [44]:
arr[-1::-2]

array([29, 27, 25, 23, 21, 19, 17, 15, 13])

In [46]:
arr[-1:-8:-1]

array([29, 28, 27, 26, 25, 24, 23])

In [47]:
arr=np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [48]:
arr[[2,4,9]]

array([ 4,  8, 18])

In [49]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
mat[1][2]

6

In [51]:
mat[0][0]

1

In [52]:
mat[2]

array([7, 8, 9])

In [53]:
mat[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [54]:
mat[1:2,1:2]

array([[5]])

In [56]:
mat[0,1]=35
mat

array([[ 1, 35,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [57]:
mat[1,1]=20
mat

array([[ 1, 35,  3],
       [ 4, 20,  6],
       [ 7,  8,  9]])

In [58]:
mat[2,1]=25
mat


array([[ 1, 35,  3],
       [ 4, 20,  6],
       [ 7, 25,  9]])

Subseting